Cnum 28.09
koja5/custom_management pull request #106
Opened 2022-10-12 23:36 UTC by MaksimovicUros

I've added possibility when creating new voucher to send info via E-mail or sms

2022-10-19 11:42 UTC, Lazarevicka requested changes

2022-10-19 11:42 UTC, Lazarevicka commented on server/routes/ftpUploadSMS.js
> -  host: "116.203.85.82",
Comment smtp local setup, and use production. First get latest from MergeBranch

2022-10-19 11:42 UTC, Lazarevicka commented on src/app/component/dashboard/vaucher/vaucher.component.ts
> +    if (this.toSendSms) {
I would say it is better to first create voucher and then to send email. Easily can happen that mail is sent and voucher not created. Please check this.

2022-10-19 11:42 UTC, Lazarevicka commented on src/app/component/dashboard/vaucher/vaucher.component.ts
> +  toSendEmail: boolean = false;
I don't see that this variable is used anywhere to decide to sent email. Shouldn't be if(email) then sent email, and if (sms) sent SMS. SMS part is okay, it is there, but email I didn't find

2022-10-21 06:52 UTC, koja5 approved these changes

2022-10-21 08:14 UTC, merged