feat(CN-114): added feature for saving email/sms drafts and dropdown fields changed to multiselect
koja5/custom_management pull request #109
Opened 2022-10-18 12:04 UTC by INX1

2022-10-19 06:52 UTC, koja5 commented on server/routes/api.js
> +      birthdayFrom: req.body.birthdayFrom,
We have here an identical object with the same property.
Why do we additional mapped property?
For example, if we need to add a new property in this way we need to change it in three places (front, back, and database).
Why we didn't create SQL query and send a directly req.body object?
**insert email_drafts set ? where id = '" + req.body.id + "'", req,body**
This also applies to other methods

2022-10-19 06:56 UTC, koja5 commented on src/app/component/dashboard/marketing/massive-email/massive-email.component.scss
> +.button-padding > button {
This looks like the same code, but repeated two times(for email and SMS). Why?
Why we don't make this one global SCSS file and use one code in different places...

2022-10-19 07:00 UTC, koja5 commented on src/app/component/dashboard/marketing/massive-email/massive-email.component.ts
> +  getEmailDrafts(selectNewlyCreated?: boolean) {
All these new functions also repeat two times(for email and SMS). It looks pretty the same.
It's problem for future development and maintenance. If we need to change something or add, we need to do it on a few places.
If the same code repeats a few times it does not need to be copy-paste into different components.
It's needed to make reusable components (or services).

2022-10-19 07:04 UTC, koja5 requested changes
Please check the comments. Some parts need to change.
Also, you have a change in the database, but you didn't give me SQL queries for it.
Check again our **step-by-step deploy document** on Jira.
This is an example of how @Lazarevicka describes hew pull request:

Deploy:
API
client
Translation
changes to DB, take a look at the file
[CN-13.txt](https://github.com/koja5/custom_management/files/9710372/CN-13.txt)

2022-10-19 18:48 UTC, INX1 commented
I did some changes to make it more reusable now, but some things need to be the same because of local states of components. In order to not have some copies, we would need to refactor this components into one and that would take a lot of time and is not in scope of this task

2022-10-26 21:01 UTC, koja5 approved these changes

2022-10-26 21:01 UTC, koja5 approved these changes

2022-10-26 21:10 UTC, merged