Cn 182/add validation for required fields on scheduler popup
koja5/custom_management pull request #113
Opened 2022-10-26 17:08 UTC by INX1

Deploy:
client

2022-10-26 21:26 UTC, koja5 requested changes
Required changes. Check comment on jira...

2022-11-01 22:12 UTC, koja5 requested changes
We have some conflict in component. Please check.

2022-11-02 13:06 UTC, INX1 commented
fixed merge conflict

2022-11-03 08:43 UTC, koja5 approved these changes

2022-11-03 08:43 UTC, merged