feat(CN-85): error message on invalid form field
koja5/custom_management pull request #92
Opened 2022-09-06 09:12 UTC by INX1

- added error message on invalid form field

2022-09-18 07:46 UTC, koja5 requested changes
Need to add for all forms(like dynamic etc.) and please resolved the conflict.

2022-10-07 13:56 UTC, Lazarevicka commented
The changes look good, and I checked several forms it is okay. 
One small change that is needed is to include "This field is required." text like a translation key. 
The reason is on that way we will have a translation in other supported languages. Also, the message should support also a bad format. 

![image](https://user-images.githubusercontent.com/43242464/194570633-e9cc1c9b-a3ae-44d4-934b-0e71eb97ee7c.png)

2022-10-10 11:32 UTC, Lazarevicka approved these changes
The translation key is added. Approved

2022-10-10 20:33 UTC, koja5 approved these changes

2022-10-10 20:33 UTC, merged